[workspace]
members = ["boo-core", "boo"]
resolver = "2"

[workspace.dependencies]
boo-core = { path = "./boo-core" }
nvim-oxi = { version = "0.5.1", features = [
  "mlua",
  "libuv",
  "neovim-nightly",
  "neovim-0-10",
  "neovim-0-9",
] }
